stages:
  - build
  - push

variables:
  AWS_REGION: "ap-northeast-1" # 使用するAWSリージョンを指定

docker-build-job:
  stage: build
  tags:
    - airoa
  only:
    - develop
  script:
    - export SECRET_VALUE=$(aws secretsmanager get-secret-value --secret-id prd/docker-hsr-io/admin-pass --query SecretString --output text)
    - echo $SECRET_VALUE | docker login -u hsr-admin --password-stdin docker.hsr.io
    # Build the daemon container
    - docker build --build-arg GIT_HASH=$CI_COMMIT_SHA --build-arg GIT_BRANCH=$CI_COMMIT_BRANCH -t docker.hsr.io/hsrb/robot_data_pipeline_autouploader:daemon-$CI_COMMIT_BRANCH -f Dockerfile.daemon .
    # Build the client TUI container
    - docker build --build-arg GIT_HASH=$CI_COMMIT_SHA --build-arg GIT_BRANCH=$CI_COMMIT_BRANCH -t docker.hsr.io/hsrb/robot_data_pipeline_autouploader:client-$CI_COMMIT_BRANCH -f Dockerfile.client .

docker-push-job:
  stage: push
  tags:
    - airoa
  only:
    - develop
  script:
    - export SECRET_VALUE=$(aws secretsmanager get-secret-value --secret-id prd/docker-hsr-io/admin-pass --query SecretString --output text)
    - echo $SECRET_VALUE | docker login -u hsr-admin --password-stdin docker.hsr.io
    # Push daemon container
    - docker push docker.hsr.io/hsrb/robot_data_pipeline_autouploader:daemon-$CI_COMMIT_BRANCH
    # Push client container
    - docker push docker.hsr.io/hsrb/robot_data_pipeline_autouploader:client-$CI_COMMIT_BRANCH
