version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: autoloader-minio
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - autoloader-network

  createbuckets:
    image: minio/mc:latest
    container_name: autoloader-createbuckets
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/autoloader-bucket;
      /usr/bin/mc policy set public myminio/autoloader-bucket;
      exit 0;
      "
    networks:
      - autoloader-network

networks:
  autoloader-network:
    driver: bridge

volumes:
  minio_data: